name: Monthly or Manual Dataset Update

on:
  schedule:
    - cron: '0 0 28 * *'
  workflow_dispatch:

jobs:
  run-generate-datasets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set environment variables
        run: |
          echo "OPENROUTER_API_KEY=${{ secrets.OPENROUTER_API_KEY }}" >> $GITHUB_ENV
          echo "OPENROUTER_BASE_URL=${{ secrets.OPENROUTER_BASE_URL }}" >> $GITHUB_ENV
          echo "LLM_MODEL=${{ secrets.LLM_MODEL }}" >> $GITHUB_ENV
          echo "JSEARCH_API_KEY=${{ secrets.JSEARCH_API_KEY }}" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run monthly update script
        run: python utils/generate_all_datasets.py

